name: Markdownlint on PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/pr-markdownlint.yml
      - "**/*.md"

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: '**/*.md'
          config: '.github/workflows/markdownlint-cli2.jsonc'
